volumes:
  db:

services:
  app:
    container_name: todo_app
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    links:
      - db
    restart: always
    
  db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
    - db:/data/db
    command: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_INITDB_DATABASE: ${MONGODB_DATABASE}
    